spring:
  r2dbc:
    enabled: true
    url: r2dbc:postgresql://localhost:5432/practice-reactive-spring
    username: postgres
    password: root

#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG
